### ISSUE TITLE
request to release version 1.4

### ISSUE THREAD

**Issue by dbyron0** [ruby-amqp/rabbitmq_http_api_client#12]
With version 1.3 I get a conflict over multi_json that the HEAD of master (https://github.com/ruby-amqp/rabbitmq_http_api_client/commit/76021cd07c1c8b5dae5577302d4aef445711b597) resolves.

Thanks much.

**Comment by michaelklishin** [comment]
[Done](https://rubygems.org/gems/rabbitmq_http_api_client/versions/1.4.0).

**Comment by dbyron0** [comment]
So fast!  Thanks.
