### ISSUE TITLE
Hosts containing path

### ISSUE THREAD

**Issue by polmiro** [ruby-amqp/rabbitmq_http_api_client#15]
Currently BigWig RabbitMQ provides URIs that contain a path on it. It doesn't work with rabbitmq_http_api_client and Faraday. Spefically, this [issue](https://github.com/lostisland/faraday/issues/466) talks about how a connection needs to be initialized to have ```path_prefix```.

I'm going to be working on a PR for this. I'm thinking of:
* taking the path from the URI provided
* checking if it contains the "/api" RabbitMQ management url's, appending it if necessary.
* the path_prefix along to the Faraday connection initialization.

Let me know if you have any feedback on this.

**Comment by michaelklishin** [comment]
@polmiro sounds good, thank you for looking into this!
