### ISSUE TITLE
support optional parameters, e.g. columns

### ISSUE THREAD

**Issue by msayler** [ruby-amqp/rabbitmq_http_api_client#29]
Per [RMQ Management HTTP API](https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_6/priv/www/api/index.html):

> Many URIs return lists. [...] You can also restrict what information is returned per item with the columns parameter. This is a comma-separated list of subfields separated by dots. See the example below.

It would be great if I could, for example, say something like`client.list_queues(:columns=>["name","messages"])` This particular use case can reduce both client and server load when incurred when doing monitoring checks using the client for clusters with 100s or 1000s of queues.

**Comment by michaelklishin** [comment]
I wouldn't expect effect beyond JSON serialization taking less time because [columns are filtered out after querying](https://github.com/rabbitmq/rabbitmq-management/blob/c8d1d3d3f9a872a7b58a18bed4545bb59d53c903/src/rabbit_mgmt_util.erl#L243) and most of the time is spend loading and aggregating a lot of data that sorting might require.

**Comment by msayler** [comment]
Fair that it might be equivalent load on the server, but it definitely reduces load on the client when using this library. We measured a 3MB JSON output for `/api/queues` returning ~1500 items. The `list_queues` call took about 13 seconds of wall clock time at ~100% CPU on a c4.large instance in AWS. After returning only the needed columns, the wall-clock time for the whole process of connect, retrieve, and filter was less than a second.

**Comment by msayler** [comment]
I'm happy to put a change together, BTW. I just wanted to see whether it had a chance of landing.

**Comment by michaelklishin** [comment]
I don't have any objections if we can avoid breaking the API.

**Comment by sharshenov** [comment]
Fixed by https://github.com/ruby-amqp/rabbitmq_http_api_client/pull/43
```ruby
client.list_queues(vhost, columns: 'name,messages')
# or for default vhost
client.list_queues(nil, columns: 'name,messages')
```

**Comment by michaelklishin** [comment]
Thanks @sharshenov 👍
