### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by olleolleolle** [ruby-amqp/rabbitmq_http_api_client#33]
This issue is about a deprecation warning.

See https://github.com/ruby-amqp/rabbitmq_http_api_client/blob/master/lib/rabbitmq/http/client.rb#L421

Example error message:

> /home/travis/build/ruby-amqp/march_hare/vendor/bundle/jruby/2.3.0/gems/rabbitmq_http_api_client-1.9.1/lib/rabbitmq/http/client.rb:421:in
>  `uri_encode': warning: URI.escape is obsolete

**Comment by michaelklishin** [comment]
Before you look into replacing it, please beware of earlier attempts: https://github.com/ruby-amqp/rabbitmq_http_api_client/commit/b7e645dfe3358f6fae9c24444c98fccc25b4231e. I'm not following Ruby's stdlib evolution closely but a couple of years ago there were no drop-in replacements for `URI.escape` for this library's needs.

**Comment by michaelklishin** [comment]
Addressed in master by introducing a new dependency.
