### ISSUE TITLE
{bad_header,<<"PUT /api">>}

### ISSUE THREAD

**Issue by deemytch** [ruby-amqp/rabbitmq_http_api_client#35]
archlinux, erlang-nox 20.3.7-1, rabbitmq 3.7.5-1, ruby 2.5.1p57
gems versions after running `bundle update`

    $ grep rabbitmq_http_api_client Gemfile.lock
        rabbitmq_http_api_client (1.9.1)

    $ grep faraday Gemfile.lock
        faraday (0.13.1)
        faraday_middleware (0.12.2)
          faraday (>= 0.7.4, < 1.0)
          faraday (~> 0.13.0)
          faraday_middleware (~> 0.12.0)

ruby code

    require 'rabbitmq/http/client'
    client = RabbitMQ::HTTP::Client.new('http://127.0.0.1:5672', username: 'guest', password: 'guest')
    client.create_vhost( 'chat' )
    Faraday::ConnectionFailed: Connection reset by peer
    from /usr/lib/ruby/2.5.0/socket.rb:452:in `__read_nonblock'

And what in the /var/log/rabbitmq/node.log

    2018-06-25 23:50:06.279 [info] <0.13072.0> accepting AMQP connection <0.13072.0> (127.0.0.1:38678 -> 127.0.0.1:5672)
    2018-06-25 23:50:06.279 [warning] <0.13072.0> closing AMQP connection <0.13072.0> (127.0.0.1:38678 -> 127.0.0.1:5672):
    {bad_header,<<"PUT /api">>}

**Comment by michaelklishin** [comment]
If you take a closer look at the log lines they mention an "AMQP connection". You are using an HTTP API client which, as the name suggests, uses a different protocol: HTTP.

See the list of [protocols and their ports](https://www.rabbitmq.com/networking.html) in RabbitMQ documentation and post questions to the ruby-amqp mailing list (or rabbitmq-users) in the future.

**Comment by michaelklishin** [comment]
The very first example for this library [uses a URI with an explicitly specified port](https://github.com/ruby-amqp/rabbitmq_http_api_client#specifying-endpoint-and-credentials).

**Comment by ally9335** [comment]
@deemytch when will you return me $200 that you owe me for the work?
