### ISSUE TITLE
Faraday upgrade

### ISSUE THREAD

**Issue by joergd** [ruby-amqp/rabbitmq_http_api_client#46]
This is still requiring quite an old version of Faraday, which is forcing me to use older versions of other gems in my project.

**Comment by michaelklishin** [comment]
Duplicate of https://github.com/ruby-amqp/rabbitmq_http_api_client/pull/45.

This is open source software, consider submitting a PR next time instead of asking others to make a reasonably straightforward change.

**Comment by michaelklishin** [comment]
`1.14.0` is [up on RubyGems](https://rubygems.org/gems/rabbitmq_http_api_client/versions/1.14.0).

**Comment by joergd** [comment]
Thank you - much appreciated. And yes you're right - it was a bit lazy of me.
