### ISSUE TITLE
decode_resource fails when response.body is nil

### ISSUE THREAD

**Issue by sergio91pt** [ruby-amqp/rabbitmq_http_api_client#52]
With the introduction of v1.15.0, some errors started appearing on CI builds of a project using this library for tests. The errors are related to the decode_resource method of the `http/client.rb`, which seem to indicate that `response.body` is nil.

https://github.com/ruby-amqp/rabbitmq_http_api_client/blob/685769752e2bc7a1ad64c9b40366038f2f69c2b8/lib/rabbitmq/http/client.rb#L429

```
NoMethodError:
  undefined method `empty?' for nil:NilClass
# /bundle/ruby/2.4.0/gems/rabbitmq_http_api_client-1.15.0/lib/rabbitmq/http/client.rb:429:in `decode_resource'
# /bundle/ruby/2.4.0/gems/rabbitmq_http_api_client-1.15.0/lib/rabbitmq/http/client.rb:134:in `delete_exchange'
# ./spec/support/helpers/rabbitmq_management.rb:11:in `block in delete_exchanges'
# ./spec/support/helpers/rabbitmq_management.rb:11:in `each'
# ./spec/support/helpers/rabbitmq_management.rb:11:in `delete_exchanges'
# ./spec/integration/consumer/event_consumer_spec.rb:27:in `block (2 levels) in <top (required)>'
```

The CI job used faraday 1.3.0, faraday-net_http 1.0.1 and faraday_middleware 1.0.0.
Downgrading this library to v1.14.0 fixed the problem.

**Comment by PedroMGSilva** [comment]
PR with the fix: https://github.com/ruby-amqp/rabbitmq_http_api_client/issues/52

**Comment by michaelklishin** [comment]
Addressed in https://github.com/ruby-amqp/rabbitmq_http_api_client/commit/0bc48fab99d76a53d7d946405eaefdd28c084898
