### ISSUE TITLE
Avoid Faraday deprecation warning about #basic_auth

### ISSUE THREAD

**Issue by olleolleolle** [ruby-amqp/rabbitmq_http_api_client#56]
rabbitmq_http_api_client uses Faraday, and Faraday is moving towards a slightly newer way of expressing "basic auth" in connections.

> WARNING: `Faraday::Connection#basic_auth` is deprecated; it will be removed in version 2.0.
> While initializing your connection, use `#request(:basic_auth, ...)` instead.
> See https://lostisland.github.io/faraday/middleware/authentication for more usage info.

**Comment by kimgust** [comment]
https://github.com/ruby-amqp/rabbitmq_http_api_client/commit/8755cec2d6fc0aec6d4b26a58630c6c89eb971e7

**Comment by olleolleolle** [comment]
Fixed in https://github.com/ruby-amqp/rabbitmq_http_api_client/commit/8755cec2d6fc0aec6d4b26a58630c6c89eb971e7
